import Hero from 'component/components/Hero'
import Service from 'component/components/Service'
import Head from 'next/head'

export default function Home() {
  return (
    <>
      <Head>
        <title>Travel Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Hero heading="Travel is a therapy" message="Explore the world to keep you alive" />
     <Service/>
    </>
  )
}
